#!/bin/bash

for file in files/*; do
    prefix=$(basename "$file" | cut -c1)
    
    if [ -d "$prefix" ]; then
        mv "$file" "$prefix/"
    else
        mkdir "$prefix"
        mv "$file" "$prefix/"
    fi
done
